# Generated by Django 3.2 on 2023-01-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='personal_goal',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=8),
        ),
    ]
