# Generated by Django 3.2 on 2023-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20230121_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.TextField(default='', max_length=30),
        ),
    ]
