# Generated by Django 3.2 on 2023-01-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
