# Generated by Django 3.2 on 2023-01-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_is_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
