# Generated by Django 3.2 on 2023-01-22 11:53

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(choices=[('RBC', 'RBC'), ('TD', 'TD'), ('NB', 'National Bank'), ('BMO', 'BMO'), ('SC', 'Scotia Bank')], default='RBC', max_length=30)),
                ('card_number', models.CharField(default=0, max_length=30)),
                ('card_type', models.CharField(choices=[('Debit', 'Debit Card'), ('Credit', 'Credit Card')], default='Credit', max_length=6)),
                ('card_balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One-time', max_length=17)),
                ('date_of_expense', models.DateField()),
                ('is_income', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Food', 'Food'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], max_length=13)),
                ('alternative_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('alternative_name', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.card')),
            ],
        ),
    ]
