# Generated by Django 3.2 on 2023-01-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Income', 'Income'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Income', 'Income')], max_length=13),
        ),
    ]
