# Generated by Django 3.2 on 2023-01-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[('', '----'), ('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One-time', max_length=17),
        ),
    ]
