# Generated by Django 3.2 on 2023-01-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230121_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
