# Generated by Django 3.2 on 2023-01-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_expenses_category'),
        ('transactions', '0002_auto_20230121_2257'),
    ]

    operations = [
    ]
