# Generated by Django 3.2 on 2023-01-21 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_merge_20230121_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Income', 'Income'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment')], max_length=13),
        ),
    ]
