# Generated by Django 3.2 on 2023-01-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_expenses_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, choices=[('', '----'), ('Food', 'Food'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Bi-Weekly', 'Bi-Weekly'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One-time', max_length=17),
        ),
    ]
