# Generated by Django 3.2 on 2023-01-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_card_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[(1, 'Debit Card'), (0, 'Credit Card')], default=0, max_length=2),
        ),
    ]
