# Generated by Django 3.2 on 2023-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_card_card_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('Debit', 'Debit Card'), ('Credit', 'Credit Card')], default='Credit', max_length=6),
        ),
    ]
