# Generated by Django 3.2 on 2023-01-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_expenses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='source',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
