# Generated by Django 3.2 on 2023-01-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20230122_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One-time', max_length=17),
        ),
    ]
