# Generated by Django 3.2 on 2023-01-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_expenses_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='alternative_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='expenses',
            name='alternative_name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
