# Generated by Django 3.2 on 2023-01-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_auto_20230121_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='is_recurring',
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[(1, 'One-time purchase'), (52, 'Weekly'), (12, 'Monthly'), (1, 'Yearly')], default=12, max_length=7),
        ),
    ]
