# Generated by Django 3.2 on 2023-01-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20230121_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Miscellaneous')], default='House', max_length=13),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[(1, 'One-time purchase'), (52, 'Weekly'), (12, 'Monthly'), (1, 'Yearly')], default=1, max_length=7),
        ),
    ]
