# Generated by Django 3.2 on 2023-01-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_remove_expenses_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'One-time purchase'), (52, 'Weekly'), (12, 'Monthly'), (1, 'Yearly')], default=1),
        ),
    ]
