# Generated by Django 3.2 on 2023-01-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_auto_20230121_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenses',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(choices=[('Royal Bank of Canada', 'RBC'), ('Toronto Dominion', 'TD'), ('National Bank', 'National Bank'), ('Bank of Montreal', 'BMO'), ('Scotia Bank', 'Scotia Bank')], default='Royal Bank of Canada', max_length=30),
        ),
    ]
