# Generated by Django 3.2 on 2023-01-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20230121_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='bank_name',
            field=models.CharField(choices=[('RBC', 'RBC'), ('TD', 'TD'), ('NB', 'National Bank'), ('BMO', 'BMO'), ('SC', 'Scotia Bank')], default='RBC', max_length=30),
        ),
    ]
