# Generated by Django 3.2 on 2023-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_alter_card_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Yearly')], max_length=13),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[('One-time purchase', 'One-time purchase'), (365, 'Daily'), (52, 'Weekly'), (12, 'Monthly'), (1, 'Yearly')], default='One-time purchase', max_length=17),
        ),
    ]
