# Generated by Django 3.2 on 2023-01-21 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_card_card_type'),
        ('transactions', '0014_auto_20230121_1920'),
    ]

    operations = [
    ]
