# Generated by Django 3.2 on 2023-01-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_merge_20230121_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Income', 'Income'), ('Housing', 'Housing'), ('Entertainment', 'Entertainment'), ('Miscellaneous', 'Yearly')], max_length=13),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='frequency',
            field=models.CharField(choices=[('One-time', 'One-time'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='One-time', max_length=17),
        ),
    ]
